version: '3'

services:
  postgres:
    image: postgres
    container_name: flow_order
    environment:
      POSTGRES_DATABASE: floworder
      POSTGRES_USER: floworder
      POSTGRES_PASSWORD: floworder
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq_flow_order
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: floworder
      RABBITMQ_DEFAULT_PASS: floworder
